name: Build and run sanitizers

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    strategy:
      matrix:
        array: [
          { platform: "ubuntu-latest", compiler: "gcc", type: "ASan" },
          { platform: "ubuntu-latest", compiler: "gcc", type: "UBSan" },
          { platform: "ubuntu-latest", compiler: "aarch64-linux-gnu-gcc", type: "Debug" },
          { platform: "ubuntu-latest", compiler: "clang", type: "ASan" },
          { platform: "ubuntu-latest", compiler: "clang", type: "UBSan" },
          { platform: "macos-latest", compiler: "clang", type: "ASan" },
          { platform: "macos-latest", compiler: "clang", type: "UBSan" },
          { platform: "windows-latest", compiler: "gcc", type: "ASan" },
          { platform: "windows-latest", compiler: "gcc", type: "UBSan" }
        ]
      fail-fast: false
    runs-on: ${{ matrix.array.platform }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      if: ${{ matrix.array.compiler == 'aarch64-linux-gnu-gcc' }}

    - name: Set up cross-compiler
      if: ${{ matrix.array.compiler == 'aarch64-linux-gnu-gcc' }}
      run: |
        sudo dpkg --add-architecture arm64
        cat << HEREDOC | sudo tee /etc/apt/sources.list
        deb [arch=amd64,i386] http://azure.archive.ubuntu.com/ubuntu focal main universe multiverse
        deb [arch=amd64,i386] http://azure.archive.ubuntu.com/ubuntu focal-updates main universe multiverse
        deb [arch=amd64,i386] http://azure.archive.ubuntu.com/ubuntu focal-backports main universe multiverse
        deb [arch=amd64,i386] http://azure.archive.ubuntu.com/ubuntu focal-security main universe multiverse
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ focal main  universe multiverse
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ focal-updates main universe multiverse
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ focal-backports main universe multiverse
        deb [arch=arm64] http://ports.ubuntu.com/ubuntu-ports/ focal-security main universe multiverse
        HEREDOC
        sudo apt-get update -qy
        sudo apt-get install -qy crossbuild-essential-arm64 libc6:arm64 libasan5:arm64 libubsan1:arm64 luajit

    - name: Set up Cygwin
      uses: cygwin/cygwin-install-action@v1
      with:
        packages: gcc-core make cmake
      if: ${{ matrix.array.platform == 'windows-latest' }}

    - name: Configure CMake
      run: bash -c 'cmake -B ./build -DCMAKE_BUILD_TYPE=$TYPE -DHAVE_SANITIZER=1'
      env:
        CC: ${{matrix.array.compiler}}

    - name: Build
      run: bash -c 'cmake --build ./build --parallel'

    - name: Run Smoke Test
      run: bash -c './build/exprjit_smoke'

    - name: Run Benchmark
      run: bash -c './build/exprjit_benchmark'
      if: ${{ matrix.array.compiler != 'aarch64-linux-gnu-gcc' }}
      
