name: Build and run sanitizers

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    strategy:
      matrix:
        compiler: [gcc, clang]
        type: [ASan, UBSan]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.type}} -DHAVE_SANITIZER=1
      env:
        CC: ${{matrix.compiler}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.type}} --parallel $(nproc --all)

    - name: Run
      working-directory: ${{github.workspace}}/build
      run: |
        ./exprjit_test
        ./exprjit_smoke
        ./exprjit_benchmark
      
